planning_plugin: ompl_interface/OMPLPlanner

request_adapters: >-
  default_planning_request_adapters/ResolveConstraintFrames
  default_planning_request_adapters/ValidateWorkspaceBounds
  default_planning_request_adapters/CheckStartStateBounds
  default_planning_request_adapters/CheckStartStateCollision

response_adapters: >-
  default_planning_response_adapters/AddTimeOptimalParameterization
  default_planning_response_adapters/ValidateSolution
  default_planning_response_adapters/DisplayMotionPath

# CRITICAL: This must be under ompl: namespace
ompl:
  planner_configs:
    RRTConnect:
      type: geometric::RRTConnect
    RRT:
      type: geometric::RRT
    RRTstar:
      type: geometric::RRTstar

  left_arm:
    planner_configs:
      - RRTConnect
      - RRT
    default_planner_config: RRTConnect
    projection_evaluator: joints(left_shoulder_pan_joint,left_shoulder_lift_joint)

  right_arm:
    planner_configs:
      - RRTConnect
      - RRT
    default_planner_config: RRTConnect
    projection_evaluator: joints(right_shoulder_pan_joint,right_shoulder_lift_joint)

  both_arms:
    planner_configs:
      - RRTConnect
    default_planner_config: RRTConnect
    projection_evaluator: joints(left_shoulder_pan_joint,left_shoulder_lift_joint)