sensors:
  - pointcloud
pointcloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /camera/depth/points
  max_range: 5.0
  min_range: 0.1
  padding_offset: 0.05
  padding_scale: 1.0
  max_update_rate: 1.0
  filtered_cloud_topic: /camera/points_filtered