joint_limits:
  left_shoulder_pan_joint: {has_velocity_limits: true, max_velocity: 2.0}
  left_shoulder_lift_joint: {has_velocity_limits: true, max_velocity: 2.0}
  left_elbow_joint: {has_velocity_limits: true, max_velocity: 2.0}
  left_wrist_1_joint: {has_velocity_limits: true, max_velocity: 2.0}
  left_wrist_2_joint: {has_velocity_limits: true, max_velocity: 2.0}
  left_wrist_3_joint: {has_velocity_limits: true, max_velocity: 2.0}

  right_shoulder_pan_joint: {has_velocity_limits: true, max_velocity: 2.0}
  right_shoulder_lift_joint: {has_velocity_limits: true, max_velocity: 2.0}
  right_elbow_joint: {has_velocity_limits: true, max_velocity: 2.0}
  right_wrist_1_joint: {has_velocity_limits: true, max_velocity: 2.0}
  right_wrist_2_joint: {has_velocity_limits: true, max_velocity: 2.0}
  right_wrist_3_joint: {has_velocity_limits: true, max_velocity: 2.0}