planning_plugin: ompl_interface/OMPLPlanner

request_adapters: >-
  default_planning_request_adapters/ResolveConstraintFrames
  default_planning_request_adapters/ValidateWorkspaceBounds
  default_planning_request_adapters/CheckStartStateBounds
  default_planning_request_adapters/CheckStartStateCollision

response_adapters: >-
  default_planning_response_adapters/AddTimeOptimalParameterization
  default_planning_response_adapters/ValidateSolution
  default_planning_response_adapters/DisplayMotionPath

planner_configs:
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.2
  RRT:
    type: geometric::RRT
    range: 0.2
    goal_bias: 0.1
  PRMstar:
    type: geometric::PRMstar

arm:
  planner_configs:
    - RRTConnect
    - RRT
    - PRMstar
  default_planner_config: RRTConnect
  projection_evaluator:  joints(shoulder_pan_joint,shoulder_lift_joint)
  longest_valid_segment_fraction: 0.005